
services:
  proxy-gateway:
    container_name: proxy-gateway
    build: .
    ports:
      - "5000-5055:5000-5055"
    environment:
      START_PORT: 5000
      END_PORT: 5055
      CLIENT_USER: FW5eg15et5g
      CLIENT_PASS: Yuk65swfAc15rd56jtn1
      REMOTE_USER: WFKwk538ejfjkwd
      REMOTE_PASS: df6fc62s5643ge56
      REMOTE_PORT: 3715
      API_URL: https://api.runonflux.io/apps/location/proxypoolusa
    volumes:
      - ./configs:/configs
    restart: unless-stopped