version: "3.8"

services:
  proxy-gateway:
    container_name: proxy-gateway
    build: .
    ports:
      - "5000-5099:5000-5099"
    environment:
      CLIENT_USER: user123
      CLIENT_PASS: pass228
      REMOTE_USER: fs2d1sf1sf
      REMOTE_PASS: HBFW4d41scdas
      REMOTE_PORT: 3406
      API_URL: https://api.runonflux.io/apps/location/ProxyServerXXX50030
      START_PORT: 5000
    restart: unless-stopped
