version: "3.8"

services:
  proxy-gateway:
    container_name: proxy-gateway
    build: .
    ports:
      - "5000-5099:5000-5099"
    environment:
      CLIENT_USER: user
      CLIENT_PASS: pass
      REMOTE_USER: proxyuser
      REMOTE_PASS: proxypass
      REMOTE_PORT: 3406
      API_URL: https://api.runonflux.io/apps/location/ProxyServerXXX50030
      START_PORT: 5000
    restart: unless-stopped
