
services:
  proxy-gateway:
    container_name: proxy-gateway
    build: .
    ports:
      - "5000-5055:5000-5055"
    environment:
      START_PORT: 5000
      END_PORT: 5055
      CLIENT_USER: username
      CLIENT_PASS: pass
      REMOTE_USER: proxyuser
      REMOTE_PASS: proxypass
      REMOTE_PORT: 3715
      API_URL: https://api.runonflux.io/apps/location/yourapp
    volumes:
      - ./configs:/configs
    restart: unless-stopped
